package com.app.user.constants;

public interface ResponseKeysValue {

	String SUCCESS_STATUS_CODE_200 = "200";
	String SUCCESS_STATUS_DESCRIPTION_200 = "SUCCESS";
	String SUCCESS_STATUS_CODE_201 = "201";
	String SUCCESS_STATUS_DESCRIPTION_201 = "CREATED SUCCEFULLY";
	String FAILURE_STATUS_CODE_500 = "500";
	String FAILURE_STATUS_DESCRIPTION_500 = "FAILURE";
	String FAILURE_STATUS_CODE_400 = "400";
	String FAILURE_STATUS_DESCRIPTION_400 = "INVALIDE INPUT DATA";
	String FAILURE_STATUS_CODE_401 = "401";
	String FAILURE_STATUS_DESCRIPTION_401 = "AUTHENTICATION FAIL";
	String FAILURE_LOGIN_DESCRIPTION_401 = "WRONG LOGIN CREDENTIAL";
	String FAILURE_OTP_DESCRIPTION = "OTP SENDING PROCESS FAIL";
	String SUCCESS_OTP_DESCRIPTION = "OTP SENT SUCCESSFULLY";
	String FAILURE_PASS_CPASS_DESCRIPTION = "PASSWORD AND CONFIRM PASSWORD ARE NOT SAME";
	String FAILURE_MPIN_CMPIN_DESCRIPTION = "MPIN AND CONFIRM MPIN ARE NOT SAME";

	/* WARNING */
	String WARNING_MULTIPLE_DEVICE_LOGIN_DESCRIPTION_401 = "DO YOU WANT TO LOGOUT FROM OTHER DEVICE?";
	String WARNING_MULTIPLE_DEVICE_LOGIN_STATUS_401 = "100";
	String WARNING_MPIN_GENERATION_DESCRIPTION = "NEED TO GENERATE MPIN";
	String WARNING_MPIN_GENERATION_STATUS = "100";

	String SUCCESS_LOGOUT_STATUS_STATUS_201 = "201";
	String SUCCESS_LOGOUT_STATUS_DESCRIPTION_201 = "LOGOUT SUCCEFULLY";

	String SUCCESS_LOGIN_STATUS_STATUS_200 = "200";
	String SUCCESS_LOGIN_STATUS_DESCRIPTION_200 = "LOGIN SUCCEFULLY";

	String SUCCESS_FORGET_PASSWORD_STATUS_CODE_200 = "200";
	String SUCCESS_FORGET_PASSWORD_STATUS_DESCRIPTION_200 = "FORGET PASSWORD PROCCESS SUCCESS";

	String FAILURE_DATA_NOT_FOUNT_DESCRIPTION_500 = "DATA NOT FOUND";

	String WARNING_USER_ALREADY_EXIST_CODE = "100";
	String WARNING_USER_ALREADY_EXIST_DESC = "User Already Exist";

	String WARNING_USER_EMAIL_NOT_EXIST_CODE = "104";
	String WARNING_USER_EMAIL_NOT_EXIST_DESC = "User Email Does Not Exist";

	String WARNING_WRONG_OLD_PASSWORD_CODE = "104";
	String WARNING_WRONG_OLD_PASSWORD_DESC = "Wrong Old Password";

	String SUCCESS_CHANGE_PASSWORD_STATUS_CODE_200 = "200";
	String SUCCESS_CHANGE_PASSWORD_STATUS_DESCRIPTION_200 = "CHANGE PASSWORD PROCCESS SUCCESS";

	String WARNING_CLIENT_ALREADY_EXIST_CODE = "100";
	String WARNING_CLIENT_ALREADY_EXIST_DESC = "Client Already Exist";

	String WARNING_CLIENT_DOESNT_EXIST_CODE = "100";
	String WARNING_CLIENT_DOESNT_EXIST_DESC = "Client doesn't Exist";

	// String SUCCESS_STATUS_DESCRIPTION_USER_UPDATE="User details Updated
	// Successfully";
	// String SUCCESS_STATUS_DESCRIPTION_USER_CREATE="User Registration Success";

}
