package com.app.user.constants;

public interface ScreenRouteConstant {
	String MPIN_LOGIN_SCREEN_ID="0001";
	String MPIN_LOGIN_SCREEN_DESC="MPIN LOGIN SCREEN";
	String MPIN_REGISTRATION_SCREEN_ID="0002";
	String MPIN_REGISTRATION_SCREEN_DESC="MPIN REGISTRATION SCREEN";
	String DASHBOARD_SCREEN_ID="0003";
	String DASHBOARD_SCREEN_DESC="DASHBOARD SCREEN";
	String LOGIN_SCREEN_ID="0004";
	String LOGIN_SCREEN_DESC=" LOGIN SCREEN";


}
